# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aa508b43f0db8f11bcf766320f5575a99a29be1b6b05e5c02cf1df940d5d8037719223f19180e7514ab5b3e533b9d2bb787d0faefb7e26a20413ac40dcbbf8bc

test:
  secret_key_base: 7c338cb18074e13fe171a69d8cae65384eb0f9f60b88f5115b989a8c3e03c2c0abe204a2faac5c34ecfc3313b2182ab978ea9f1d93d95ec704aa204cabd403bc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
